// <auto-generated />
using EFApp.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFApp2.Migrations.TptDb
{
    [DbContext(typeof(TptDbContext))]
    [Migration("20250620160013_InitialCreate_TPT")]
    partial class InitialCreate_TPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFApp.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lab8_TPT_Manufacturers", (string)null);
                });

            modelBuilder.Entity("EFApp.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Lab8_TPT_Ships_Base", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFApp.Models.Aircarrier", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("AircraftCapacity")
                        .HasColumnType("int");

                    b.ToTable("Lab8_TPT_Aircarriers", (string)null);
                });

            modelBuilder.Entity("EFApp.Models.Battleship", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("MainCaliberGuns")
                        .HasColumnType("int");

                    b.ToTable("Lab8_TPT_Battleships", (string)null);
                });

            modelBuilder.Entity("EFApp.Models.Cruiser", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("MissileCount")
                        .HasColumnType("int");

                    b.ToTable("Lab8_TPT_Cruisers", (string)null);
                });

            modelBuilder.Entity("EFApp.Models.Destroyer", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("TorpedoTubes")
                        .HasColumnType("int");

                    b.ToTable("Lab8_TPT_Destroyers", (string)null);
                });

            modelBuilder.Entity("EFApp.Models.Submarine", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("MaxDepth")
                        .HasColumnType("int");

                    b.ToTable("Lab8_TPT_Submarines", (string)null);
                });

            modelBuilder.Entity("EFApp.Models.Ship", b =>
                {
                    b.HasOne("EFApp.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("EFApp.Models.Aircarrier", b =>
                {
                    b.HasOne("EFApp.Models.Ship", null)
                        .WithOne()
                        .HasForeignKey("EFApp.Models.Aircarrier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFApp.Models.Battleship", b =>
                {
                    b.HasOne("EFApp.Models.Ship", null)
                        .WithOne()
                        .HasForeignKey("EFApp.Models.Battleship", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFApp.Models.Cruiser", b =>
                {
                    b.HasOne("EFApp.Models.Ship", null)
                        .WithOne()
                        .HasForeignKey("EFApp.Models.Cruiser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFApp.Models.Destroyer", b =>
                {
                    b.HasOne("EFApp.Models.Ship", null)
                        .WithOne()
                        .HasForeignKey("EFApp.Models.Destroyer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFApp.Models.Submarine", b =>
                {
                    b.HasOne("EFApp.Models.Ship", null)
                        .WithOne()
                        .HasForeignKey("EFApp.Models.Submarine", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
