// <auto-generated />
using EFApp.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFApp2.Migrations
{
    [DbContext(typeof(TphDbContext))]
    [Migration("20250620155957_InitialCreate_TPH")]
    partial class InitialCreate_TPH
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFApp.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lab8_TPH_Manufacturers", (string)null);
                });

            modelBuilder.Entity("EFApp.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Lab8_TPH_Ships", (string)null);

                    b.HasDiscriminator<string>("ShipType").HasValue("Ship");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFApp.Models.Aircarrier", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("AircraftCapacity")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Aircarrier");
                });

            modelBuilder.Entity("EFApp.Models.Battleship", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("MainCaliberGuns")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Battleship");
                });

            modelBuilder.Entity("EFApp.Models.Cruiser", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("MissileCount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Cruiser");
                });

            modelBuilder.Entity("EFApp.Models.Destroyer", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("TorpedoTubes")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Destroyer");
                });

            modelBuilder.Entity("EFApp.Models.Submarine", b =>
                {
                    b.HasBaseType("EFApp.Models.Ship");

                    b.Property<int>("MaxDepth")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Submarine");
                });

            modelBuilder.Entity("EFApp.Models.Ship", b =>
                {
                    b.HasOne("EFApp.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
